### ISSUE TITLE
Allow pacts to be published to a broker with a custom certificate

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-ruby-standalone#11]
SSL_CERT_FILE and SSL_CERT_DIR are cleared by Travelling Ruby. Find out why this is done, and if it can be skipped.

**Comment by winfieldaj** [comment]
@bethesque I am not sure if there is a difference in "pact-standalone" and "pact-ruby-standalone" but I found this issue in pact-standalone.

The issue is in the @pact-foundation\pact-standalone\platforms\win32\lib\ruby\bin\ruby.bat. As well as in the respective files for the other OSs.

In my testing, if I have preset the "SSL_CERT_FILE" to a private cert file it is over written by line 22.

Possible fix would be to not set this if it already contains a value.

**Comment by bethesque** [comment]
It should be fixed now. Have a look at the referenced commit.

**Comment by bethesque** [comment]
Which Wrapper language are you using?

**Comment by bethesque** [comment]
If you're after pact-js, a new version has been released. Let me know how it goes.

**Comment by winfieldaj** [comment]
@bethesque Sorry for the delay. I am currently waiting on my build team to white list this version and put it in our nexus repository so I can test on our linux build platform. It is looking like that is not going to happen until sometime next week so I will test then and report back.

I am using pact-js

**Comment by adambbn** [comment]
I can confirm this is still relevant. `SSL_CERT_FILE` is overwritten to `...\pact\lib\ruby\bin\..\lib\ca-bundle.crt` when running pact-provider-verifier.bat.
Running pact-1.64.1-win32 on Windows 10.
